### ISSUE TITLE
Missing KneeLocalizer function

### ISSUE THREAD

**Issue by kuhlaid** [epierson9/pain-disparities#2] opened 2021-09-28 13:44 UTC
Hi @epierson9 
I am looking through the image_processing.py code and the repository seems to be missing a 'detector' module as referenced in line 107 of image_processing.py. 

`from detector import KneeLocalizer`

The 'KneeLocalizer' function but it does not appear in the any of the repository scripts and 'detector' does not appear to be an external package since it is not mentioned in 'requirements.txt'.

**Comment by epierson9** [comment] 2021-09-28 13:50
Thanks for pointing this out! The KneeLocalizer functionality is not used in the final paper, which is why that import is wrapped in an if statement and not included in requirements.txt; you will not need the import unless the if statement runs, so I'd suggest setting the flag to false if you want to reproduce our results. If you _do_ want to use that code, you can find it here - https://github.com/MIPT-Oulu/KneeLocalizer.

**Comment by epierson9** [comment] 2021-09-28 13:50
Closing this issue for now - feel free to reopen if you have further questions!

**Closed as completed by epierson9** 2021-09-28 13:50 UTC

**Comment by kuhlaid** [comment] 2021-09-28 17:05
Thank you @epierson9. 

I'm trying to run 
`python image_processing.py`
and it hits line 181
`results = self.knee_localizer.predict(dicom_image_path)`
but knee_localizer is not defined (since 'crop_to_just_the_knee' is defaulted to false). Didn't you have to run this code at some point?

**Comment by epierson9** [comment] 2021-09-28 17:15
Ah, good point. I pushed a tweak - see the latest commit. (Basically, I removed the knee localizer import after running the data processing, prior to the final release, to minimize the dependencies.) If you run into further knee localizer issues, I think it should be fine to either 1) download the repo I linked to above or 2) just comment out the code which uses the knee localizer.

**Comment by kuhlaid** [comment] 2021-09-29 12:41
Hi @epierson9,
I'm slowly progressing through this image processing and have another question. I am still only trying to execute
`python image_processing.py` successfully at this point and line 131 of image_processing.py `self.compute_dataset_image_statistics_and_divide_by_max(just_normalize_cropped_knees=True)` seems to suggest that this code is expecting the cropped knees to be present (which I do not have at the moment). Am I reading this wrong or is something else going on?

If I need to crop the knee images first you might want to add a note about that in the data processing section of the README.
- thank you for your time

**Comment by epierson9** [comment] 2021-09-29 13:07
Thanks! Yeah, again, I think one of the two solutions I propose above should work re: cropped knees - either download the KneeLocalizer repo, or comment out the code which makes used of cropped knees. It's seeming like the first solution might be easier, so please let me know if you have issues which aren't fixed by that!

**Comment by epierson9** [comment] 2021-09-29 13:15
I will modify the code in the next week - probably I will just add the KneeLocalizer to the dependencies - but the fixes proposed above should resolve your issue in the meantime. Thanks for raising this!

**Comment by epierson9** [comment] 2021-09-29 13:51
I added back in the KneeLocalizer dependency, and updated the image processing code and README. If the KneeLocalizer repo proves too annoying for others to set up, I'll remove references to it as discussed above; it's not essential to our pipeline.

**Comment by kuhlaid** [comment] 2021-09-29 21:02
Thank you @epierson9. I tried working with the KneeLocalizer but if you didn't use it in your analysis then I will comment it out. I hit an error of `ValueError: too many values to unpack (expected 2)' on line 185 of `image_processing.py` and I'm not sure it is worth trying to resolve at the moment.

**Comment by epierson9** [comment] 2021-09-29 21:19
Yeah, I'd comment it out, then - that's caused by a slightly different version of the KneeLocalizer code which returns one fewer argument. Feel free to issue a PR with whatever version of the code you get to run.
